/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    DatabaseForm: typeof import('./src/components/DatabaseForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Image: typeof import('primevue/image')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
