/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DatabaseForm: typeof import('./src/components/DatabaseForm.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    FieldItem: typeof import('./src/components/FieldItem.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GISMap: typeof import('./src/components/GISMap.vue')['default']
    HeaderPanel: typeof import('./src/components/HeaderPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Panel: typeof import('primevue/panel')['default']
    PrimeTable: typeof import('./src/components/PrimeTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesRatio: typeof import('./src/components/SalesRatio.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
